pair/pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos", include("todos.urls")),
]

pair/todos/urls.py
from django.urls import path
from . import views


app_name = "todos"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk_>", views.detail, name="detail"),
    path("edit/<int:pk_>", views.edit, name="edit"),
    path("update/<int:pk_>", views.update, name="update"),
    path("delete/<int:todo_pk>", views.delete, name="delete"),
]

pair/todos/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    # django에서 pk(id)는 자동으로 만들어준다.
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(auto_now=True)

pair/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.


def index(request):
    todos = Todo.objects.all()
    context = {
        "todos": todos,
    }
    return render(request, "todos/index.html", context)


def new(request):
    return render(request, "todos/new.html")


def create(request):
    # 1. parameter로 날라온 데이터를 DB에 저장
    title = request.GET.get("title___")
    content = request.GET.get("content___")

    # 2. DB에 저장
    Todo.objects.create(title=title, content=content)

    return redirect("todos:index")


def detail(request, pk_):
    todo = Todo.objects.get(pk=pk_)
    context = {
        "todo": todo,
    }
    return render(request, "todos/detail.html", context)


def edit(request, pk_):
    todo = Todo.objects.get(pk=pk_)
    context = {
        "todo": todo,
    }
    return render(request, "todos/edit.html", context)


def update(request, pk_):
    # update할 특정 데이터를 불러온다 -> pk_를 사용해서
    todo = Todo.objects.get(pk=pk_)
    title_ = request.GET.get("title___")
    content_ = request.GET.get("content___")

    # 데이터를 수정
    todo.title = title_
    todo.content = content_

    # 데이터를 수정한 것을 반영(save)
    todo.save()

    # 데이터의 디테일 페이지로 리다이렉트
    return redirect("todos:detail", todo.pk)


def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()

    return redirect("todos:index")

pair/todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <h1>선택한 글 세부내용</h1><br>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">할 일</label>
        <input type="text" readonly class="form-control" id="exampleFormControlInput1" value="{{todo.title}}">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">할 일 내용</label>
        <input type="text" readonly class="form-control" id="exampleFormControlInput1" value="{{todo.content}}">
    </div>

    <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" href="{% url 'todos:edit' todo.pk %}" role="button">수정하기</a>
        <a class="btn btn-outline-danger" href="{% url 'todos:delete' todo.pk %}" role="button">삭제하기</a>
        <a class="btn btn-outline-primary" href="{% url 'todos:index' %}" role="button">목록으로</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

pair/todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <h1>선택한 글 수정</h1>
    <form action="{% url 'todos:update' todo.pk %}" onsubmit="return check()" name='myform'>
        <div class="col-12">
            <label for="inputAddress" class="form-label">제목</label>
            <input type="text" class="form-control" name="title___" id="inputAddress" placeholder=""
                value="{{todo.title}}">
        </div>
        <div class="col-12">
            <label for="inputAddress2" class="form-label">내용</label>
            <textarea class="form-control" placeholder="" name="content___" id=""
                style="height: 165px;">{{todo.content}}</textarea>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-outline-primary">리뷰작성</button>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <script>
            //체크 함수 생성
            function check() {
             //myfrom 이름 설정
              var f = document.myform;

              if (f.title___.value == "") {
                  alert("제목을 입력해주십시오");
                  f.title___.focus();
                  return false;
              }
                if (f.content___.value == "") {
                  alert("내용을 입력해주세요");
                  f.content___.focus();
                  return false;
              }
      
      }
      </script>
</body>

</html>

pair/todos/templates/todos/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>

    <h1>영화 리뷰 페이지</h1>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">리뷰 번호</th>
            <th scope="col">리뷰 제목</th>
            <th scope="col">작성 시간</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry the Bird</td>
            <td>Larry the Bird</td>
          </tr>
        </tbody>
      </table>
        



</body>

</html>

pair/todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <form action="{% url 'todos:create' %}" onsubmit="return check()" name='myform'>
        <div class="col-12">
            <label for="inputAddress" class="form-label">제목</label>
            <input type="text" class="form-control" name="title___" id="inputAddress" placeholder="">
        </div>
        <div class="col-12">
            <label for="inputAddress2" class="form-label">내용</label>
            <textarea class="form-control" placeholder="" name="content___" id="floatingTextarea"
                style="height: 165px;"></textarea>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-outline-primary">리뷰작성</button>
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
        <script>
            //체크 함수 생성
            function check() {
             //myfrom 이름 설정
              var f = document.myform;

              if (f.title___.value == "") {
                  alert("제목을 입력해주십시오");
                  f.title___.focus();
                  return false;
              }
                if (f.content___.value == "") {
                  alert("내용을 입력해주세요");
                  f.content___.focus();
                  return false;
              }
      
      }
      </script>
</body>

</html>